### PR TITLE
nginx timings parser

### PR DESCRIPTION
**Pull request by benrudolph**
@snopoke here's my first go at creating a custom parser. i'm little confused on how it will look in datadog, but i'm assuming we'll be able to aggregate by the attributes i've defined. does that sound right to you? i'd like to have it so amelia could potentially filter by a url and see the average response time month to month. even better would be able to compare based on url, so like, what's the slowest url for the month of october (ansible portion coming soon to a theater near you)

### CODE REVIEW

**Comment by benrudolph** [comment]
(tests pass, didn't setup travis)

**Comment by snopoke** [comment]
Looks good. I'm not sure about the attributes. I suspect that having that many different values may not be good. Best option is to ask support (email or live chat): https://app.datadoghq.com/help

**Comment by benrudolph** [comment]
cool, will do thanks

**Comment by benrudolph** [comment]
have a ticket pending with datadog to get this resolved

**Comment by benrudolph** [comment]
err the ticket was never resolved, i don't think they have much experience in this area. i was told to do some trials, so i'm gonna go ahead and merge and test out on staging

**Pull request merged**
